# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46378492540555e4448d09c66a73af41f556f20a3b8b8d414acf0a397a3c192b502e150bd3f024659e85fc455b5f913b2add570173ec57d8b48859a128d7835b

test:
  secret_key_base: 516b1005beb8536e08add0bb238b034db15090ef576faf7f5ed6d7beb59c4bccd2754663c3ce1fc6add339e15d523b61af05ae5d7be5a37b245f9f6513993513

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
